services:
  backend:
    build:
      context: ./backend
    container_name: steam-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./steam-data-frontend
    container_name: steam-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
